# name: SSH Deployment

# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Check out code
#       uses: actions/checkout@v4

#     - name: SSH and run commands
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.SSH_HOST }}
#         username: ${{ secrets.SSH_USERNAME }}
#         password: ${{ secrets.SSH_PASSWORD }}
#         port: ${{ secrets.SSH_PORT }}
#         script: |
#           git clone git@github.com:NT-Tien/capstone-backend-2024.git
#           cp api/.env capstone-backend-2024/.env &&
#           cd capstone-backend-2024 &&
#           docker-compose down &&
#           docker rmi capstone-backend-2024-backend:latest &&
#           docker-compose up --build -d &&
#           cd .. &&
#           rm -rf capstone-backend-2024
name: SSH Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: SSH and run commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cp api/.env capstone-backend-2024/.env &&
          cd capstone-backend-2024 &&
          docker-compose down &&
          docker rmi capstone-backend-2024-backend:latest &&
          docker-compose up --build -d &&